create table if not exists public.garimpeiro_snapshots (
  id bigint generated by default as identity primary key,
  product_key text not null,
  collected_at timestamptz not null default now(),
  source text not null default 'auto_discovery',
  category text,
  keyword text,
  payload jsonb not null
);

create index if not exists idx_garimpeiro_snapshots_product_key
  on public.garimpeiro_snapshots (product_key);

create index if not exists idx_garimpeiro_snapshots_collected_at
  on public.garimpeiro_snapshots (collected_at desc);

alter table public.garimpeiro_snapshots enable row level security;

-- O app Streamlit deve usar a SERVICE ROLE KEY guardada em Secrets.
-- A service role ignora RLS. Não publique essa chave no GitHub.
